a=eval(input("First number is : "))
b=eval(input("Second number is :"))
print("Addition of two number is",a+b)
print("Addition of",a,"and",b,"is",a+b)
print("Addition of {} and {} is {}".format(a,b,a+b))
print(f"Addition of {a} and {b} is {a+b}")
print("Addition of %d and %d is %d"%(a,b,a+b))
print("\n")
print("Subtraction of two number is",a-b)
print("Subtraction of",a,"and",b,"is",a-b)
print("Subtraction of {} and {} is {}".format(a,b,a-b))
print(f"Subtraction of {a} and {b} is {a+b}")
print("Subtraction of %d and %d is %d"%(a,b,a-b))
print("\n")
print("Multiplication of two number is",a*b)
print("Multiplication of",a,"and",b,"is",a*b)
print("Multiplication of {} and {} is {}".format(a,b,a*b))
print(f"Multiplication of {a} and {b} is {a*b}")
print("Multiplication of %d and %d is %d "%(a,b,a*b))
print("\n")
print("Division of two number is",a/b)
print("Division of",a,"and",b,"is",a/b)
print("Division of {} and {} is {}".format(a,b,a/b))
print(f"Division of {a} and {b} is {a/b}")
print("Division of %d and %d is %d"%(a,b,a/b))
print("\n")
print("Power of a^b number is",a**b)
print("Power of",a,"^",b,"is",a**b)
print("Power of {}^{} is {}".format(a,b,a**b))
print(f"Power of {a}^ {b} is {a+b}")
print("Power of %d^%d is %d"%(a,b,a**b))
print("\n")
print("Integer Division of two number is",a//b)
print("Integer Division of",a,"and",b,"is",a//b)
print("Integer Division of {} and {} is {}".format(a,b,a//b))
print(f"Interger Division of {a} and {b} is {a//b}")
print("Interger Division of %d and %d is %d"%(a,b,a//b))
