length=eval(input("Enter the Length of Cuboid :"))
breath=eval(input("Enter the Breath of Cuboid :"))
height=eval(input("Enter the Height of Cuboid :"))
print(f"Volume of Cuboid is {length*breath*height}")
print(f"TSA of Cuboid is {2*(length*breath+breath*height+length*height)}")
